name: Build OpenWrt EN7523

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            flex \
            bison \
            g++ \
            gawk \
            gettext \
            git \
            libncurses-dev \
            libssl-dev \
            python3 \
            python3-setuptools \
            rsync \
            unzip \
            zlib1g-dev \
            file \
            wget \
            curl \
            subversion \
            swig \
            time \
            xsltproc \
            libelf-dev

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 \
            https://github.com/openwrt/openwrt.git \
            openwrt

      - name: Update feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Check EN7523 DTS
        working-directory: openwrt
        run: |
          find target/linux/airoha -iname '*en7523*'

          test -f target/linux/airoha/dts/en7523-evb.dts

      - name: Copy custom config
        run: |
          echo "Repository root:"
          ls -la "$GITHUB_WORKSPACE"

          test -f "$GITHUB_WORKSPACE/.config"

          cp "$GITHUB_WORKSPACE/.config" \
             "$GITHUB_WORKSPACE/openwrt/.config"

          echo "Config copied successfully."

      - name: Prepare config
        working-directory: openwrt
        run: |
          make defconfig

      - name: Download sources
        working-directory: openwrt
        run: |
          make download -j$(nproc)

      - name: Build
        working-directory: openwrt
        run: |
          make -j$(nproc) V=s

      - name: Show output
        working-directory: openwrt
        run: |
          echo "===== Firmware ====="
          find bin/targets -type f -print

          echo
          echo "===== DTB ====="
          find build_dir \
            -type f \
            -name 'en7523-evb.dtb' \
            -print

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: en7523-firmware
          path: |
            openwrt/bin/targets/airoha/en7523/**
          if-no-files-found: error

      - name: Upload DTS
        uses: actions/upload-artifact@v4
        with:
          name: en7523-dtb
          path: |
            openwrt/target/linux/airoha/dts/en7523-evb.dts
          if-no-files-found: error
